blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01P (MQTT Topic Trigger)
  description: Triggers actions based on the raw MQTT 'action' topic published by the SNZB-01P via Zigbee2MQTT.
  domain: automation
  input:
    remote_entity:
      name: Sonoff SNZB-01P Action Entity
      description: The entity that publishes the 'action' state (e.g., sensor.your_device_name_action). This is typically created automatically by Z2M/MQTT Discovery.
      selector:
        entity:
          integration: mqtt
          domain: sensor
          # Filter for entities with 'action' in the name/device class, common for buttons
          multiple: false
    single_press_action:
      name: Single Press Action
      description: Action to run when the state is 'single'.
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to run when the state is 'double'.
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action (Hold)
      description: Action to run when the state is 'long'.
      default: []
      selector:
        action: {}

mode: single

trigger:
  # Trigger when the state of the action entity changes to 'single', 'double', or 'long'
  - platform: state
    entity_id: !input 'remote_entity'

action:
  - variables:
      action_state: "{{ trigger.to_state.state }}"
  - choose:
      # Action: single
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'single' }}"
        sequence: !input 'single_press_action'
      # Action: double
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'double' }}"
        sequence: !input 'double_press_action'
      # Action: long
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'long' }}"
        sequence: !input 'long_press_action'
