blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01P (Manual MQTT Topic)
  description: Triggers actions based on the full JSON payload published by the SNZB-01P via Zigbee2MQTT. Requires the device's base MQTT topic (e.g., 'zigbee2mqtt/my_button_name').
  domain: automation
  input:
    mqtt_base_topic:
      name: Device MQTT Base Topic
      description: Enter the full MQTT base topic for your device (e.g., zigbee2mqtt/bedroom_button).
      selector:
        text: {}
    single_press_action:
      name: Single Press Action
      description: Action to run when the 'action' is 'single'.
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to run when the 'action' is 'double'.
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action (Hold)
      description: Action to run when the 'action' is 'long'.
      default: []
      selector:
        action: {}

mode: single

trigger:
  # Trigger on any message published to the base topic
  - platform: mqtt
    topic: !input 'mqtt_base_topic'
    id: 'mqtt_trigger'

action:
  # Extract the 'action' value from the JSON payload (e.g., "single", "double", "long")
  - variables:
      action_state: "{{ trigger.payload_json.action }}"
  - choose:
      # Action: single
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'single' }}"
        sequence: !input 'single_press_action'
      # Action: double
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'double' }}"
        sequence: !input 'double_press_action'
      # Action: long
      - conditions:
          - condition: template
            value_template: "{{ action_state == 'long' }}"
        sequence: !input 'long_press_action'
