blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01P (Press/Double/Hold)
  description: Perform actions with the Sonoff SNZB-01P Button using Zigbee2MQTT. This blueprint maps single, double, and long press actions to separate configurable sequences.
  domain: automation
  input:
    remote_device:
      name: Sonoff SNZB-01P Device
      description: The Sonoff SNZB-01P button device from Zigbee2MQTT.
      selector:
        device:
          integration: mqtt
          manufacturer: SONOFF
          model: SNZB-01P
          multiple: false
    single_press_action:
      name: Single Press Action
      description: Action to run on a single press (quick click).
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to run on a double press (two quick clicks).
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action (Hold)
      description: Action to run on a long press (holding the button down).
      default: []
      selector:
        action: {}

mode: single

trigger:
  # Trigger for Single Press (Subtype 'single' corresponds to action: "single" in Z2M payload)
  - platform: device
    domain: mqtt
    device_id: !input 'remote_device'
    type: action
    subtype: single
    id: 'single'

  # Trigger for Double Press (Subtype 'double' corresponds to action: "double" in Z2M payload)
  - platform: device
    domain: mqtt
    device_id: !input 'remote_device'
    type: action
    subtype: double
    id: 'double'

  # Trigger for Long Press (Subtype 'long' corresponds to action: "long" in Z2M payload)
  - platform: device
    domain: mqtt
    device_id: !input 'remote_device'
    type: action
    subtype: long
    id: 'long'

action:
  # Choose the action sequence based on which trigger fired
  - choose:
      - conditions:
          - condition: trigger
            id: 'single'
        sequence: !input 'single_press_action'
      - conditions:
          - condition: trigger
            id: 'double'
        sequence: !input 'double_press_action'
      - conditions:
          - condition: trigger
            id: 'long'
        sequence: !input 'long_press_action'
